import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./reset.min.css";
import "./globals.css";
import "./common.css";
import Header from "@/components/common/Header/Header";
import Footer from "@/components/common/Footer/Footer";

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${notoSansJP.variable} antialiased` }
      >
        <Header />
        <main className="py-12 mt-32">
          {children}
        </main>
        <Footer />
        <div className="bg"></div>
      </body>
    </html>
  );
}
